//Maincategory
export const CREATE_MAINCTEGORY = "CREATE_MAINCTEGORY";
export const CREATE_MAINCTEGORY_RED = "CREATE_MAINCTEGORY_RED";
export const GET_MAINCTEGORY = "GET_MAINCTEGORY"
export const GET_MAINCTEGORY_RED = "GET_MAINCTEGORY_RED"
export const UPDATE_MAINCTEGORY = "UPDATE_MAINCTEGORY"
export const UPDATE_MAINCTEGORY_RED = "UPDATE_MAINCTEGORY_RED"
export const DELETE_MAINCTEGORY = "DELETE_MAINCTEGORY"
export const DELETE_MAINCTEGORY_RED = "DELETE_MAINCTEGORY_RED"

// Subcategory
export const CREATE_SUBCTEGORY = "CREATE_SUBCTEGORY";
export const CREATE_SUBCTEGORY_RED = "CREATE_SUBCTEGORY_RED";
export const GET_SUBCTEGORY = "GET_SUBCTEGORY"
export const GET_SUBCTEGORY_RED = "GET_SUBCTEGORY_RED"
export const UPDATE_SUBCTEGORY = "UPDATE_SUBCTEGORY"
export const UPDATE_SUBCTEGORY_RED = "UPDATE_SUBCTEGORY_RED"
export const DELETE_SUBCTEGORY = "DELETE_SUBCTEGORY"
export const DELETE_SUBCTEGORY_RED = "DELETE_SUBCTEGORY_RED"

// Brand

export const CREATE_BRAND = "CREATE_BRAND";
export const CREATE_BRAND_RED = "CREATE_BRAND_RED";
export const GET_BRAND = "GET_BRAND"
export const GET_BRAND_RED = "GET_BRAND_RED"
export const UPDATE_BRAND = "UPDATE_BRAND"
export const UPDATE_BRAND_RED = "UPDATE_BRAND_RED"
export const DELETE_BRAND = "DELETE_BRAND"
export const DELETE_BRAND_RED = "DELETE_BRAND_RED"

// Testimonial

export const CREATE_TESTIMONIAL = "CREATE_TESTIMONIAL";
export const CREATE_TESTIMONIAL_RED = "CREATE_TESTIMONIAL_RED";
export const GET_TESTIMONIAL = "GET_TESTIMONIAL"
export const GET_TESTIMONIAL_RED = "GET_TESTIMONIAL_RED"
export const UPDATE_TESTIMONIAL = "UPDATE_TESTIMONIAL"
export const UPDATE_TESTIMONIAL_RED = "UPDATE_TESTIMONIAL_RED"
export const DELETE_TESTIMONIAL = "DELETE_TESTIMONIAL"
export const DELETE_TESTIMONIAL_RED = "DELETE_TESTIMONIAL_RED"

// Product 
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const CREATE_PRODUCT_RED = "CREATE_PRODUCT_RED";
export const GET_PRODUCT = "GET_PRODUCT"
export const GET_PRODUCT_RED = "GET_PRODUCT_RED"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const UPDATE_PRODUCT_RED = "UPDATE_PRODUCT_RED"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const DELETE_PRODUCT_RED = "DELETE_PRODUCT_RED"

// Contractus 
export const CREATE_CONTRACTUS = "CREATE_CONTRACTUS";
export const CREATE_CONTRACTUS_RED = "CREATE_CONTRACTUS_RED";
export const GET_CONTRACTUS = "GET_CONTRACTUS"
export const GET_CONTRACTUS_RED = "GET_CONTRACTUS_RED"
export const UPDATE_CONTRACTUS = "UPDATE_CONTRACTUS"
export const UPDATE_CONTRACTUS_RED = "UPDATE_CONTRACTUS_RED"
export const DELETE_CONTRACTUS = "DELETE_CONTRACTUS"
export const DELETE_CONTRACTUS_RED = "DELETE_CONTRACTUS_RED"

// cart 
export const CREATE_CART = "CREATE_CART";
export const CREATE_CART_RED = "CREATE_CART_RED";
export const GET_CART = "GET_CART"
export const GET_CART_RED = "GET_CART_RED"
export const UPDATE_CART = "UPDATE_CART"
export const UPDATE_CART_RED = "UPDATE_CART_RED"
export const DELETE_CART = "DELETE_CART"
export const DELETE_CART_RED = "DELETE_CART_RED"

// wishlist 
export const CREATE_WISHLIST = "CREATE_WISHLIST";
export const CREATE_WISHLIST_RED = "CREATE_WISHLIST_RED";
export const GET_WISHLIST = "GET_WISHLIST"
export const GET_WISHLIST_RED = "GET_WISHLIST_RED"
export const DELETE_WISHLIST = "DELETE_WISHLIST"
export const DELETE_WISHLIST_RED = "DELETE_WISHLIST_RED"

// checkout 
export const CREATE_CHECKOUT = "CREATE_CHECKOUT";
export const CREATE_CHECKOUT_RED = "CREATE_CHECKOUT_RED";
export const GET_CHECKOUT = "GET_CHECKOUT"
export const GET_CHECKOUT_RED = "GET_CHECKOUT_RED"
export const UPDATE_CHECKOUT = "UPDATE_CHECKOUT"
export const UPDATE_CHECKOUT_RED = "UPDATE_CHECKOUT_RED"
export const DELETE_CHECKOUT = "DELETE_CHECKOUT"
export const DELETE_CHECKOUT_RED = "DELETE_CHECKOUT_RED"

// newslatter 
export const CREATE_NEWSLATTER = "CREATE_NEWSLATTER";
export const CREATE_NEWSLATTER_RED = "CREATE_NEWSLATTER_RED";
export const GET_NEWSLATTER = "GET_NEWSLATTER"
export const GET_NEWSLATTER_RED = "GET_NEWSLATTER_RED"
export const UPDATE_NEWSLATTER = "UPDATE_NEWSLATTER"
export const UPDATE_NEWSLATTER_RED = "UPDATE_NEWSLATTER_RED"
export const DELETE_NEWSLATTER = "DELETE_NEWSLATTER"
export const DELETE_NEWSLATTER_RED = "DELETE_NEWSLATTER_RED"

// Users
export const CREATE_USERS = "CREATE_USERS";
export const CREATE_USERS_RED = "CREATE_USERS_RED";
export const GET_USERS = "GET_USERS"
export const GET_USERS_RED = "GET_USERS_RED"
export const UPDATE_USERS = "UPDATE_USERS"
export const UPDATE_USERS_RED = "UPDATE_USERS_RED"
export const DELETE_USERS = "DELETE_USERS"
export const DELETE_USERS_RED = "DELETE_USERS_RED"